/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class co_com_mundocostenio_jni_ControlCedulaJni */

#ifndef _Included_co_com_mundocostenio_jni_ControlCedulaJni
#define _Included_co_com_mundocostenio_jni_ControlCedulaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     co_com_mundocostenio_jni_ControlCedulaJni
 * Method:    controloCedula
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_co_com_mundocostenio_jni_ControlCedulaJni_controloCedula
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
